[package]
name = "etf_balancer"
version = "0.1.0"
authors = ["Nathan Merritt <gnm@the-merritts.net>"]

[dependencies]
actix-web = "0.6.10"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
spectral = "0.6.0"
